refactor symlinks script

diff --git a/bin/apply_symlinks b/bin/apply_symlinks
--- a/bin/apply_symlinks
+++ b/bin/apply_symlinks
@@ -1,26 +1,31 @@
-#! /usr/bin/env bash
+#!/usr/bin/env bash
 
 # DESCRIPTION
 # Applies symlinks using stow
 
-[[ -z "${DOTFILE_DIR}" ]] && DOTFILE_DIR=$HOME/dev/dotfiles
+# This line sets shell options for safer script execution:
+# -e: Exit immediately if a command exits with a non-zero status.
+# -u: Treat unset variables as an error when substituting.
+# -o pipefail: The return value of a pipeline is the status of
+#              the last command to exit with a non-zero status,
+#              or zero if no command exited with a non-zero status.
+set -euo pipefail
 
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR asdf
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR alacritty
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR bat
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR elixir
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR eslint
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR helix
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR jetbrains
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR kitty
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR neovim
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR prettier
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR ripgrep
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR ruby
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR silver_searcher
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR tig
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR tmux
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR vim
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR yt-dlp
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR yabai
-stow -v -R --target=$HOME --dir=$DOTFILE_DIR zsh
+DOTFILE_DIR="${DOTFILE_DIR:-$HOME/dev/dotfiles}"
+TARGET_DIR="$HOME"
+
+apply_symlink() {
+  stow -v -R --target="$TARGET_DIR" --dir="$DOTFILE_DIR" "$1"
+}
+
+# List of packages to symlink
+packages=(
+  asdf alacritty aerospace bat elixir eslint helix jetbrains
+  kitty neovim prettier ripgrep ruby silver_searcher tig
+  tmux vim yt-dlp yabai zsh
+)
+
+# Apply symlinks for each package
+for package in "${packages[@]}"; do
+  apply_symlink "$package"
+done
